#!/bin/sh
### BEGIN INIT INFO
# Provides:          system
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description:       
### END INIT INFO

start_it_up()
{
  # Give write access to fpga for php
  chmod a+w /sys/class/fpga_manager/fpga0/firmware

  # Delete all old symbolic links
  find /lib/firmware -type l -delete

  # Create Links for Examples
  for file in `ls /home/median.demonstrator.internal/firmware`
  do
    ln -s -f /home/median.demonstrator.internal/firmware/${file} /lib/firmware/${file}
  done

  # Mount config filesystem for overlays
  mount -t configfs none /config
  
  # Create overlay for fclk[0-4]
  mkdir /config/device-tree/overlays/fclk
  cp /home/median.demonstrator.internal/dt-overlay/fclk/fclk.dtbo /config/device-tree/overlays/fclk/dtbo
  
  # Probe the driver
  modprobe fclk
  modprobe stpg
  modprobe pi-cam
  modprobe vio
}

shut_it_down()
{
  # Delete overlay fclk.dtbo
  rmdir /config/device-tree/overlays/vio
  rmdir /config/device-tree/overlays/median
  rmdir /config/device-tree/overlays/fclk
  
  # Unmount config filesystem
  umount /config
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  reload|force-reload)
#    reload_it
  ;;
  restart)
    shut_it_down
    start_it_up
  ;;
  status)
#    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
#    echo "Usage: /etc/init.d/$NAME {start|stop|reload|restart|force-reload|status}" >&2
    exit 2
  ;;
esac
